cache:
  directories:
    - node_modules
script:
  - git clone https://www.github.com/fedebone00/gestio-frontend
  - cp -r fedebone00/IS_Gestio gestio-frontend
  - cd gestio-frontend
  - git remote add cred https://fedebone00:${GH_KEY}@github.com/fedebone00/gestio-frontend
  - git add .
  - git commit -m "Automatic push"
  - git push origin master